### ISSUE TITLE
distinction between colon and semicolon

### ISSUE THREAD

**Issue by backwardspy** [qwerasd205/PixelCode#1]
hi, really enjoying the font so far!

i have noticed one issue that i'd like to hear your thoughts on, to my eye `:` and `;` can be tricky to tell apart.

![image](https://user-images.githubusercontent.com/289746/190244150-fa116ed7-2be0-4602-9241-424ce4141040.png)

are you interested in making these two characters a little more distinct from one another?

**Comment by qwerasd205** [comment]
I have a plan to alter the `,` and `;` styles soon for this very reason. When I release the version with the more distinct `,` style there will be a `straight comma` stylistic alternate with the old style available for those who preferred it.

**Comment by qwerasd205** [comment]
<img width="334" alt="image" src="https://user-images.githubusercontent.com/7241851/190248183-ca404dde-f1bc-4539-875d-e980cda30dc9.png">
These are the 3 styles I'm considering, if you have any opinions. Top is current, the dashed lines are baselines.
Better comparison:
<img width="396" alt="image" src="https://user-images.githubusercontent.com/7241851/190251843-dae9c554-8bb9-4b0a-bff5-f35e3a52b321.png">

**Comment by backwardspy** [comment]
i quite like the simplicity of the top option, but the second one might be more distinct at small sizes. i think it would be good to see all three in a code snippet to get a feel for each option.

**Comment by qwerasd205** [comment]
Once I get around to implementing the options I'll give some examples to compare -- these are just quickly drawn up in GIMP.

**Comment by qwerasd205** [comment]
<img width="303" alt="image" src="https://user-images.githubusercontent.com/7241851/190558673-6f781440-21cb-43b2-9566-9d3bbb856591.png">
<img width="268" alt="image" src="https://user-images.githubusercontent.com/7241851/190558716-2537e0a2-ed4a-4c2a-b135-c71e803a8dfb.png">
This definitely feels a lot more readable.

**Comment by qwerasd205** [comment]
<img width="378" alt="image" src="https://user-images.githubusercontent.com/7241851/190559136-09ac6c4c-7573-474e-a32e-fafe585b933a.png">
Curly style has a pleasant character to it, but might be a bit too much.

**Comment by qwerasd205** [comment]
New style implemented in [v.1.1.0](https://github.com/qwerasd205/PixelCode/releases/tag/v1.1.0).
![quick_brown_fox js](https://user-images.githubusercontent.com/7241851/190564304-f49148f9-87da-4f3a-a8cb-9bc31ea69a66.png)

**Comment by backwardspy** [comment]
i really like that, thank you!
