### ISSUE TITLE
Would you mind if this font was included in Nixpkgs?

### ISSUE THREAD

**Issue by mattpolzin** [qwerasd205/PixelCode#2]
I’m interested in trying your font out which means I’m also interested in packaging it for Nixpkgs if you don’t mind me doing that. It would require nothing from you nor changes to this repository; I’d be adding some code to github.com/nixos/nixpkgs to pull your font from your release artifacts.

**Comment by qwerasd205** [comment]
Feel free! I don't mind at all. ^-^
